services:
  agent1:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: zabbix-agent-1
    restart: unless-stopped
    environment:
      ZBX_HOSTNAME: "docker-agent-1"
      ZBX_SERVER_HOST: "10.0.2.15"
    ports:
      - "10151:10050"

  agent2:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: zabbix-agent-2
    restart: unless-stopped
    environment:
      ZBX_HOSTNAME: "docker-agent-2"
      ZBX_SERVER_HOST: "10.0.2.15"
    ports:
      - "10152:10050"
